# General information about the project.
project = u'OS-Railway Documentation'
copyright = u'2024, Peter Siegmund (mars3142)'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'en'
