# Importing conf_common adds all the non-language-specific
# parts to this conf module
try:
    from conf_common import *  # noqa: F403,F401
except ImportError:
    import os
    import sys
    sys.path.insert(0, os.path.abspath('../'))
    from conf_common import *  # noqa: F403,F401

import datetime

current_year = datetime.datetime.now().year

# General information about the project.
project = u'OS-Railway Documentation'
copyright = u'2024, Peter Siegmund (mars3142)'.format(current_year)

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'en'
