site_name: OS-Railway
edit_uri: https://github.com/os-railway/os-railway/blob/documentation/docs/
theme: 
  name: readthedocs
  analytics:
    gtag: G-GPW4XBJ70J
nav:
  - Home: index.md
  - Remote Control: remote-control.md
  - ICE: ice.md
  - Thomas the Tank Engine: thomas-the-tank-engine.md
