name: MkDocs Build and Deploy

on:
  push:

permissions:
  contents: write

jobs:
  build_deploy:
    name: Build and Deploy
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install mkdocs
        run: |
          python -m pip install --upgrade pip
          pip install -U mkdocs

      - name: Build and deploy website
        run: |
          git config --global user.name 'Peter Siegmund'
          git config --global user.email 'mars3142@users.noreply.github.com'
          make deploy
